[project]
name = "dmi-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Annika Segal", email = "79905405+Ann1aka@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "datetime>=6.0",
    "configparser>=7.2.0",
    "pandas>=3.0.6",
    "psycopg[binary]>=3.3.6",
    "requests>=2.34.2",
    "sqlalchemy>=2.1.1",
]

[project.scripts]
dmi-etl = "dmi_etl:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
